import type { IconName } from "@/components/icon";

export const navigation: { href: string; label: string; short: string; icon: IconName }[] = [
  { href: "/", label: "Нүүр", short: "Home", icon: "home" },
  { href: "/servers", label: "Серверүүд", short: "Servers", icon: "server" },
  { href: "/leaderboard", label: "Шилдгүүд", short: "Leaderboard", icon: "trophy" },
  { href: "/membership", label: "Гишүүнчлэл", short: "Membership", icon: "crown" },
  { href: "/clans", label: "Кланууд", short: "Clans", icon: "clan" },
  { href: "/bans", label: "Бан жагсаалт", short: "Bans", icon: "ban" },
  { href: "/skinchanger", label: "Skin Changer", short: "Changer", icon: "skin" },
  { href: "/collection", label: "Дэлгүүр", short: "Store", icon: "spark" },
  { href: "/staff", label: "Staff Team", short: "Staff", icon: "staff" },
];

export const servers = [
  { id: "01", name: "WINGS PREMIER #1", map: "ANCIENT", mode: "PREMIER", players: 8, capacity: 10, ping: 12, state: "LIVE", address: "192.0.2.10:27015", tone: "mint" },
  { id: "02", name: "WINGS PREMIER #2", map: "MIRAGE", mode: "PREMIER", players: 10, capacity: 10, ping: 9, state: "FULL", address: "192.0.2.11:27015", tone: "amber" },
  { id: "03", name: "WINGS RETAKE", map: "INFERNO", mode: "RETAKE", players: 6, capacity: 12, ping: 14, state: "LIVE", address: "192.0.2.12:27015", tone: "red" },
  { id: "04", name: "WINGS 1V1 ARENA", map: "AIM_MAP", mode: "1V1", players: 2, capacity: 8, ping: 11, state: "OPEN", address: "192.0.2.13:27015", tone: "violet" },
  { id: "05", name: "WINGS DEATHMATCH", map: "DUST II", mode: "DEATHMATCH", players: 18, capacity: 24, ping: 16, state: "LIVE", address: "192.0.2.14:27015", tone: "amber" },
  { id: "06", name: "WINGS SURF", map: "SURF_UTOPIA", mode: "SURF", players: 0, capacity: 20, ping: 13, state: "OPEN", address: "192.0.2.15:27015", tone: "cyan" },
];

export const leaders = [
  { rank: 1, name: "NOVALEX", tag: "VOID", rating: 2847, wins: 94, winRate: 78, kd: 1.42 },
  { rank: 2, name: "coldzera.mn", tag: "ECLIPSE", rating: 2055, wins: 81, winRate: 74, kd: 1.36 },
  { rank: 3, name: "kuro", tag: "PHANTOM", rating: 1860, wins: 76, winRate: 71, kd: 1.31 },
  { rank: 4, name: "S4KU", tag: "VOID", rating: 1694, wins: 69, winRate: 68, kd: 1.28 },
  { rank: 5, name: "TR1GGER", tag: "PHANTOM", rating: 1511, wins: 64, winRate: 66, kd: 1.22 },
  { rank: 6, name: "munkh.exe", tag: "ECLIPSE", rating: 1384, wins: 61, winRate: 63, kd: 1.19 },
  { rank: 7, name: "NOIR", tag: "VOID", rating: 1228, wins: 58, winRate: 61, kd: 1.17 },
  { rank: 8, name: "Vanta", tag: "PHANTOM", rating: 1080, wins: 49, winRate: 57, kd: 1.12 },
  { rank: 9, name: "horizon", tag: "VOID", rating: 930, wins: 42, winRate: 54, kd: 1.07 },
  { rank: 10, name: "KIRA", tag: "ECLIPSE", rating: 780, wins: 36, winRate: 51, kd: 1.03 },
];

export const clans = [
  { rank: 1, tag: "[WINGS]", name: "Wings Origin", members: 18, rating: 8450, wins: 47, tone: "violet" },
  { rank: 2, tag: "[MGL]", name: "Mongol Elite", members: 14, rating: 7980, wins: 42, tone: "cyan" },
  { rank: 3, tag: "[VOID]", name: "Void Walkers", members: 12, rating: 7610, wins: 39, tone: "pink" },
  { rank: 4, tag: "[NOMAD]", name: "Nomad Five", members: 9, rating: 7140, wins: 34, tone: "amber" },
];

export const bans = [
  { player: "player_8472", reason: "Cheating", admin: "WINGS AC", server: "Premier #1", date: "2026.08.24", expires: "Permanent" },
  { player: "toxic_one", reason: "Toxic behavior", admin: "Astra", server: "Retake", date: "2026.08.23", expires: "6 days" },
  { player: "smurf_008", reason: "Ban evasion", admin: "Nyx", server: "1v1 Arena", date: "2026.08.22", expires: "Permanent" },
  { player: "afk_master", reason: "Repeated griefing", admin: "Orbit", server: "Premier #2", date: "2026.08.21", expires: "2 days" },
  { player: "fake_ping", reason: "Exploit abuse", admin: "WINGS AC", server: "Deathmatch", date: "2026.08.20", expires: "14 days" },
];

export type CosmeticArtwork = { atlas: "accessories" | "wearables" | "effects"; slot: number };
export type CosmeticCategory = "Skins" | "Knives" | "Gloves" | "Stickers" | "Charms" | "Agents" | "Music Kits" | "Medals";
export type CosmeticItem = { category: CosmeticCategory; name: string; collection: string; rarity: string; tone: string; symbol: string; artwork: CosmeticArtwork; weapon?: string };

const authenticPaintKits: [string, string, string[]][] = [
  ["P2000", "P2000", ["Fire Elemental", "Imperial Dragon", "Ocean Foam", "Amber Fade"]],
  ["DUAL BERETTAS", "Dual Berettas", ["Cobra Strike", "Melondrama", "Marina", "Hemoglobin"]],
  ["P250", "P250", ["See Ya Later", "Asiimov", "Muertos", "Franklin"]],
  ["FIVE-SEVEN", "Five-SeveN", ["Hyper Beast", "Angry Mob", "Monkey Business", "Case Hardened"]],
  ["TEC-9", "Tec-9", ["Fuel Injector", "Decimator", "Nuclear Threat", "Isaac"]],
  ["CZ75-AUTO", "CZ75-Auto", ["Victoria", "Xiangliu", "The Fuschia Is Now", "Yellow Jacket"]],
  ["DESERT EAGLE", "Desert Eagle", ["Blaze", "Printstream", "Code Red", "Kumicho Dragon"]],
  ["R8 REVOLVER", "R8 Revolver", ["Fade", "Amber Fade", "Reboot", "Skull Crusher"]],
  ["MAC-10", "MAC-10", ["Neon Rider", "Stalker", "Disco Tech", "Heat"]],
  ["MP9", "MP9", ["Starlight Protector", "Mount Fuji", "Food Chain", "Rose Iron"]],
  ["MP7", "MP7", ["Bloodsport", "Nemesis", "Whiteout", "Fade"]],
  ["MP5-SD", "MP5-SD", ["Phosphor", "Agent", "Gauss", "Desert Strike"]],
  ["UMP-45", "UMP-45", ["Primal Saber", "Momentum", "Blaze", "Crime Scene"]],
  ["P90", "P90", ["Asiimov", "Death by Kitty", "Shallow Grave", "Nostalgia"]],
  ["PP-BIZON", "PP-Bizon", ["Judgement of Anubis", "High Roller", "Embargo", "Fuel Rod"]],
  ["M4A4", "M4A4", ["Howl", "Poseidon", "The Emperor", "Asiimov"]],
  ["FAMAS", "FAMAS", ["Commemoration", "Roll Cage", "Mecha Industries", "Pulse"]],
  ["GALIL AR", "Galil AR", ["Chatterbox", "Chromatic Aberration", "Eco", "Cerberus"]],
  ["AUG", "AUG", ["Akihabara Accept", "Stymphalian", "Momentum", "Chameleon"]],
  ["SG 553", "SG 553", ["Integrale", "Colony IV", "Cyrex", "Darkwing"]],
  ["SSG 08", "SSG 08", ["Dragonfire", "Blood in the Water", "Big Iron", "Fever Dream"]],
  ["SCAR-20", "SCAR-20", ["Cyrex", "Cardiac", "Bloodsport", "Enforcer"]],
  ["G3SG1", "G3SG1", ["The Executioner", "Flux", "Chronos", "High Seas"]],
  ["NOVA", "Nova", ["Hyper Beast", "Bloomstick", "Antique", "Koi"]],
  ["XM1014", "XM1014", ["Tranquility", "Incinegator", "Seasons", "Entombed"]],
  ["MAG-7", "MAG-7", ["Justice", "Monster Call", "Heat", "Cinquedea"]],
  ["SAWED-OFF", "Sawed-Off", ["The Kraken", "Apocalypto", "Wasteland Princess", "Kiss♥Love"]],
  ["M249", "M249", ["Downtown", "Emerald Poison Dart", "O.S.I.P.R.", "Nebula Crusader"]],
  ["NEGEV", "Negev", ["Mjölnir", "Power Loader", "Loudmouth", "dev_texture"]],
];

const extraWeaponSkins: CosmeticItem[] = authenticPaintKits.flatMap(([weapon, label, finishes], groupIndex) => finishes.map((finish, finishIndex) => ({
  category: "Skins",
  weapon,
  name: `${label} | ${finish}`,
  collection: "Counter-Strike 2",
  rarity: "Weapon Finish",
  tone: ["violet", "pink", "cyan", "amber", "mint", "blue"][(groupIndex + finishIndex) % 6],
  symbol: finish.slice(0, 2).toUpperCase(),
  artwork: { atlas: "effects", slot: (groupIndex + finishIndex) % 12 },
})));

export const cosmetics: CosmeticItem[] = [
  { category:"Skins",weapon:"AK-47",name:"AK-47 | Neon Revolution",collection:"The Gamma 2 Collection",rarity:"Covert",tone:"pink",symbol:"NR",artwork:{atlas:"effects",slot:0} },
  { category:"Skins",weapon:"AK-47",name:"AK-47 | The Empress",collection:"The Spectrum 2 Collection",rarity:"Covert",tone:"violet",symbol:"TE",artwork:{atlas:"effects",slot:1} },
  { category:"Skins",weapon:"AK-47",name:"AK-47 | Neon Rider",collection:"The Horizon Collection",rarity:"Covert",tone:"pink",symbol:"NR",artwork:{atlas:"effects",slot:2} },
  { category:"Skins",weapon:"AK-47",name:"AK-47 | Bloodsport",collection:"The Spectrum Collection",rarity:"Covert",tone:"red",symbol:"BS",artwork:{atlas:"effects",slot:3} },
  { category:"Skins",weapon:"AK-47",name:"AK-47 | Aquamarine Revenge",collection:"The Falchion Collection",rarity:"Covert",tone:"cyan",symbol:"AR",artwork:{atlas:"effects",slot:8} },
  { category:"Skins",weapon:"AK-47",name:"AK-47 | Redline",collection:"The Phoenix Collection",rarity:"Classified",tone:"red",symbol:"RL",artwork:{atlas:"effects",slot:9} },
  { category:"Skins",weapon:"AK-47",name:"AK-47 | Frontside Misty",collection:"The Shadow Collection",rarity:"Classified",tone:"cyan",symbol:"FM",artwork:{atlas:"effects",slot:10} },
  { category:"Skins",weapon:"AK-47",name:"AK-47 | Nightwish",collection:"Dreams & Nightmares",rarity:"Covert",tone:"violet",symbol:"NW",artwork:{atlas:"effects",slot:11} },
  { category:"Skins",weapon:"AK-47",name:"AK-47 | Head Shot",collection:"The Revolution Collection",rarity:"Covert",tone:"pink",symbol:"HS",artwork:{atlas:"effects",slot:0} },
  { category:"Skins",weapon:"AK-47",name:"AK-47 | Legion of Anubis",collection:"The Fracture Collection",rarity:"Covert",tone:"amber",symbol:"LA",artwork:{atlas:"effects",slot:1} },
  { category:"Skins",weapon:"AK-47",name:"AK-47 | Ice Coaled",collection:"The Recoil Collection",rarity:"Classified",tone:"cyan",symbol:"IC",artwork:{atlas:"effects",slot:2} },
  { category:"Skins",weapon:"AK-47",name:"AK-47 | Slate",collection:"The Snakebite Collection",rarity:"Restricted",tone:"blue",symbol:"SL",artwork:{atlas:"effects",slot:3} },
  { category:"Skins",weapon:"M4A1-S",name:"M4A1-S | Printstream",collection:"The Operation Broken Fang Collection",rarity:"Covert",tone:"violet",symbol:"PS",artwork:{atlas:"effects",slot:8} },
  { category:"Skins",weapon:"M4A1-S",name:"M4A1-S | Player Two",collection:"The Prisma 2 Collection",rarity:"Covert",tone:"pink",symbol:"P2",artwork:{atlas:"effects",slot:9} },
  { category:"Skins",weapon:"M4A1-S",name:"M4A1-S | Hyper Beast",collection:"The Chroma 2 Collection",rarity:"Covert",tone:"violet",symbol:"HB",artwork:{atlas:"effects",slot:10} },
  { category:"Skins",weapon:"M4A1-S",name:"M4A1-S | Golden Coil",collection:"The Shadow Collection",rarity:"Covert",tone:"amber",symbol:"GC",artwork:{atlas:"effects",slot:11} },
  { category:"Skins",weapon:"M4A1-S",name:"M4A1-S | Decimator",collection:"The Spectrum Collection",rarity:"Classified",tone:"cyan",symbol:"DE",artwork:{atlas:"effects",slot:0} },
  { category:"Skins",weapon:"M4A1-S",name:"M4A1-S | Mecha Industries",collection:"The Gamma Collection",rarity:"Covert",tone:"blue",symbol:"MI",artwork:{atlas:"effects",slot:1} },
  { category:"Skins",weapon:"M4A1-S",name:"M4A1-S | Nightmare",collection:"The Horizon Collection",rarity:"Classified",tone:"violet",symbol:"NM",artwork:{atlas:"effects",slot:2} },
  { category:"Skins",weapon:"M4A1-S",name:"M4A1-S | Night Terror",collection:"Dreams & Nightmares",rarity:"Restricted",tone:"red",symbol:"NT",artwork:{atlas:"effects",slot:3} },
  { category:"Skins",weapon:"M4A1-S",name:"M4A1-S | Hot Rod",collection:"The Chop Shop Collection",rarity:"Classified",tone:"red",symbol:"HR",artwork:{atlas:"effects",slot:8} },
  { category:"Skins",weapon:"M4A1-S",name:"M4A1-S | Chantico's Fire",collection:"The Chroma 3 Collection",rarity:"Covert",tone:"amber",symbol:"CF",artwork:{atlas:"effects",slot:9} },
  { category:"Skins",weapon:"M4A1-S",name:"M4A1-S | Cyrex",collection:"The Breakout Collection",rarity:"Covert",tone:"red",symbol:"CY",artwork:{atlas:"effects",slot:10} },
  { category:"Skins",weapon:"M4A1-S",name:"M4A1-S | Leaded Glass",collection:"The Spectrum 2 Collection",rarity:"Classified",tone:"cyan",symbol:"LG",artwork:{atlas:"effects",slot:11} },
  { category:"Skins",weapon:"AWP",name:"AWP | Dragon Lore",collection:"The Cobblestone Collection",rarity:"Covert",tone:"amber",symbol:"DL",artwork:{atlas:"effects",slot:0} },
  { category:"Skins",weapon:"AWP",name:"AWP | Gungnir",collection:"The Norse Collection",rarity:"Covert",tone:"cyan",symbol:"GU",artwork:{atlas:"effects",slot:1} },
  { category:"Skins",weapon:"AWP",name:"AWP | Desert Hydra",collection:"The 2021 Mirage Collection",rarity:"Covert",tone:"pink",symbol:"DH",artwork:{atlas:"effects",slot:2} },
  { category:"Skins",weapon:"AWP",name:"AWP | Asiimov",collection:"The Phoenix Collection",rarity:"Covert",tone:"amber",symbol:"AS",artwork:{atlas:"effects",slot:3} },
  { category:"Skins",weapon:"AWP",name:"AWP | Neo-Noir",collection:"The Danger Zone Collection",rarity:"Covert",tone:"violet",symbol:"NN",artwork:{atlas:"effects",slot:8} },
  { category:"Skins",weapon:"AWP",name:"AWP | Containment Breach",collection:"The Shattered Web Collection",rarity:"Covert",tone:"mint",symbol:"CB",artwork:{atlas:"effects",slot:9} },
  { category:"Skins",weapon:"AWP",name:"AWP | Hyper Beast",collection:"The Falchion Collection",rarity:"Covert",tone:"violet",symbol:"HB",artwork:{atlas:"effects",slot:10} },
  { category:"Skins",weapon:"AWP",name:"AWP | Wildfire",collection:"The CS20 Collection",rarity:"Covert",tone:"red",symbol:"WF",artwork:{atlas:"effects",slot:11} },
  { category:"Skins",weapon:"AWP",name:"AWP | Lightning Strike",collection:"The Arms Deal Collection",rarity:"Covert",tone:"violet",symbol:"LS",artwork:{atlas:"effects",slot:0} },
  { category:"Skins",weapon:"AWP",name:"AWP | Fever Dream",collection:"The Spectrum Collection",rarity:"Classified",tone:"pink",symbol:"FD",artwork:{atlas:"effects",slot:1} },
  { category:"Skins",weapon:"AWP",name:"AWP | Atheris",collection:"The Prisma Collection",rarity:"Restricted",tone:"mint",symbol:"AT",artwork:{atlas:"effects",slot:2} },
  { category:"Skins",weapon:"AWP",name:"AWP | Mortis",collection:"The Clutch Collection",rarity:"Classified",tone:"amber",symbol:"MO",artwork:{atlas:"effects",slot:3} },
  { category:"Skins",weapon:"USP-S",name:"USP-S | Printstream",collection:"The Recoil Collection",rarity:"Covert",tone:"violet",symbol:"PS",artwork:{atlas:"effects",slot:8} },
  { category:"Skins",weapon:"USP-S",name:"USP-S | Kill Confirmed",collection:"The Shadow Collection",rarity:"Covert",tone:"red",symbol:"KC",artwork:{atlas:"effects",slot:9} },
  { category:"Skins",weapon:"USP-S",name:"USP-S | The Traitor",collection:"The Snakebite Collection",rarity:"Covert",tone:"red",symbol:"TT",artwork:{atlas:"effects",slot:10} },
  { category:"Skins",weapon:"USP-S",name:"USP-S | Cortex",collection:"The Clutch Collection",rarity:"Classified",tone:"pink",symbol:"CO",artwork:{atlas:"effects",slot:11} },
  { category:"Skins",weapon:"USP-S",name:"USP-S | Neo-Noir",collection:"The Spectrum Collection",rarity:"Covert",tone:"violet",symbol:"NN",artwork:{atlas:"effects",slot:0} },
  { category:"Skins",weapon:"USP-S",name:"USP-S | Ticket to Hell",collection:"Dreams & Nightmares",rarity:"Restricted",tone:"blue",symbol:"TH",artwork:{atlas:"effects",slot:1} },
  { category:"Skins",weapon:"GLOCK-18",name:"Glock-18 | Fade",collection:"The Assault Collection",rarity:"Restricted",tone:"pink",symbol:"FA",artwork:{atlas:"effects",slot:2} },
  { category:"Skins",weapon:"GLOCK-18",name:"Glock-18 | Gamma Doppler",collection:"The 2021 Train Collection",rarity:"Covert",tone:"mint",symbol:"GD",artwork:{atlas:"effects",slot:3} },
  { category:"Skins",weapon:"GLOCK-18",name:"Glock-18 | Water Elemental",collection:"The Breakout Collection",rarity:"Classified",tone:"cyan",symbol:"WE",artwork:{atlas:"effects",slot:8} },
  { category:"Skins",weapon:"GLOCK-18",name:"Glock-18 | Vogue",collection:"The Fracture Collection",rarity:"Classified",tone:"pink",symbol:"VO",artwork:{atlas:"effects",slot:9} },
  { category:"Skins",weapon:"GLOCK-18",name:"Glock-18 | Neo-Noir",collection:"Operation Broken Fang",rarity:"Covert",tone:"violet",symbol:"NN",artwork:{atlas:"effects",slot:10} },
  { category:"Skins",weapon:"GLOCK-18",name:"Glock-18 | Bullet Queen",collection:"The Prisma 2 Collection",rarity:"Covert",tone:"amber",symbol:"BQ",artwork:{atlas:"effects",slot:11} },
  ...extraWeaponSkins,
  { category:"Knives",name:"★ Karambit | Doppler",collection:"Counter-Strike 2",rarity:"Covert",tone:"violet",symbol:"KA",artwork:{atlas:"effects",slot:0} },
  { category:"Knives",name:"★ Butterfly Knife | Fade",collection:"Counter-Strike 2",rarity:"Covert",tone:"pink",symbol:"BF",artwork:{atlas:"effects",slot:1} },
  { category:"Knives",name:"★ M9 Bayonet | Marble Fade",collection:"Counter-Strike 2",rarity:"Covert",tone:"amber",symbol:"M9",artwork:{atlas:"effects",slot:2} },
  { category:"Knives",name:"★ Bayonet | Tiger Tooth",collection:"Counter-Strike 2",rarity:"Covert",tone:"amber",symbol:"BA",artwork:{atlas:"effects",slot:3} },
  { category:"Knives",name:"★ Flip Knife | Lore",collection:"Counter-Strike 2",rarity:"Covert",tone:"mint",symbol:"FL",artwork:{atlas:"effects",slot:4} },
  { category:"Knives",name:"★ Huntsman Knife | Slaughter",collection:"Counter-Strike 2",rarity:"Covert",tone:"red",symbol:"HU",artwork:{atlas:"effects",slot:5} },
  { category:"Knives",name:"★ Stiletto Knife | Case Hardened",collection:"Counter-Strike 2",rarity:"Covert",tone:"blue",symbol:"ST",artwork:{atlas:"effects",slot:6} },
  { category:"Knives",name:"★ Talon Knife | Doppler",collection:"Counter-Strike 2",rarity:"Covert",tone:"violet",symbol:"TA",artwork:{atlas:"effects",slot:7} },
  { category:"Knives",name:"★ Skeleton Knife | Fade",collection:"Counter-Strike 2",rarity:"Covert",tone:"pink",symbol:"SK",artwork:{atlas:"effects",slot:8} },
  { category:"Knives",name:"★ Kukri Knife | Fade",collection:"Counter-Strike 2",rarity:"Covert",tone:"pink",symbol:"KU",artwork:{atlas:"effects",slot:9} },
  { category:"Gloves",name:"★ Sport Gloves | Pandora's Box",collection:"Counter-Strike 2",rarity:"Extraordinary",tone:"violet",symbol:"SG",artwork:{atlas:"wearables",slot:0} },
  { category:"Gloves",name:"★ Sport Gloves | Vice",collection:"Counter-Strike 2",rarity:"Extraordinary",tone:"pink",symbol:"SG",artwork:{atlas:"wearables",slot:1} },
  { category:"Gloves",name:"★ Sport Gloves | Hedge Maze",collection:"Counter-Strike 2",rarity:"Extraordinary",tone:"mint",symbol:"SG",artwork:{atlas:"wearables",slot:2} },
  { category:"Gloves",name:"★ Specialist Gloves | Crimson Kimono",collection:"Counter-Strike 2",rarity:"Extraordinary",tone:"red",symbol:"SP",artwork:{atlas:"wearables",slot:3} },
  { category:"Gloves",name:"★ Specialist Gloves | Fade",collection:"Counter-Strike 2",rarity:"Extraordinary",tone:"pink",symbol:"SP",artwork:{atlas:"wearables",slot:4} },
  { category:"Gloves",name:"★ Driver Gloves | King Snake",collection:"Counter-Strike 2",rarity:"Extraordinary",tone:"cyan",symbol:"DG",artwork:{atlas:"wearables",slot:5} },
  { category:"Gloves",name:"★ Driver Gloves | Snow Leopard",collection:"Counter-Strike 2",rarity:"Extraordinary",tone:"blue",symbol:"DG",artwork:{atlas:"wearables",slot:6} },
  { category:"Gloves",name:"★ Hand Wraps | Cobalt Skulls",collection:"Counter-Strike 2",rarity:"Extraordinary",tone:"blue",symbol:"HW",artwork:{atlas:"wearables",slot:7} },
  { category:"Gloves",name:"★ Moto Gloves | Spearmint",collection:"Counter-Strike 2",rarity:"Extraordinary",tone:"mint",symbol:"MG",artwork:{atlas:"wearables",slot:8} },
  { category:"Gloves",name:"★ Sport Gloves | Nocts",collection:"Counter-Strike 2",rarity:"Extraordinary",tone:"violet",symbol:"SG",artwork:{atlas:"wearables",slot:9} },
  { category:"Stickers",name:"Sticker | Crown (Foil)",collection:"Counter-Strike 2",rarity:"Foil",tone:"amber",symbol:"CR",artwork:{atlas:"accessories",slot:0} },
  { category:"Stickers",name:"Sticker | Howling Dawn",collection:"Counter-Strike 2",rarity:"Contraband",tone:"red",symbol:"HD",artwork:{atlas:"accessories",slot:1} },
  { category:"Stickers",name:"Sticker | Titan (Holo) | Katowice 2014",collection:"Katowice 2014",rarity:"Holo",tone:"cyan",symbol:"TI",artwork:{atlas:"accessories",slot:2} },
  { category:"Stickers",name:"Sticker | iBUYPOWER (Holo) | Katowice 2014",collection:"Katowice 2014",rarity:"Holo",tone:"red",symbol:"IB",artwork:{atlas:"accessories",slot:3} },
  { category:"Stickers",name:"Sticker | Natus Vincere (Holo) | Stockholm 2021",collection:"Stockholm 2021",rarity:"Holo",tone:"amber",symbol:"NV",artwork:{atlas:"accessories",slot:4} },
  { category:"Stickers",name:"Sticker | FaZe Clan (Holo) | Antwerp 2022",collection:"Antwerp 2022",rarity:"Holo",tone:"red",symbol:"FZ",artwork:{atlas:"accessories",slot:5} },
  { category:"Stickers",name:"Sticker | Team Spirit (Holo) | Copenhagen 2024",collection:"Copenhagen 2024",rarity:"Holo",tone:"blue",symbol:"TS",artwork:{atlas:"accessories",slot:6} },
  { category:"Stickers",name:"Sticker | The MongolZ (Holo) | Copenhagen 2024",collection:"Copenhagen 2024",rarity:"Holo",tone:"violet",symbol:"MZ",artwork:{atlas:"accessories",slot:7} },
  { category:"Stickers",name:"Sticker | s1mple (Gold) | Stockholm 2021",collection:"Stockholm 2021",rarity:"Gold",tone:"amber",symbol:"S1",artwork:{atlas:"accessories",slot:8} },
  { category:"Stickers",name:"Sticker | donk (Gold) | Shanghai 2024",collection:"Shanghai 2024",rarity:"Gold",tone:"amber",symbol:"DK",artwork:{atlas:"accessories",slot:9} },
  { category:"Stickers",name:"Sticker | m0NESY (Gold) | Paris 2023",collection:"Paris 2023",rarity:"Gold",tone:"amber",symbol:"M0",artwork:{atlas:"accessories",slot:10} },
  { category:"Stickers",name:"Sticker | Virtus.Pro (Holo) | Katowice 2014",collection:"Katowice 2014",rarity:"Holo",tone:"pink",symbol:"VP",artwork:{atlas:"accessories",slot:11} },
  { category:"Charms",name:"Charm | Lil' SAS",collection:"Counter-Strike 2",rarity:"High Grade",tone:"blue",symbol:"LS",artwork:{atlas:"accessories",slot:0} },
  { category:"Charms",name:"Charm | Lil' Teacup",collection:"Counter-Strike 2",rarity:"Remarkable",tone:"cyan",symbol:"LT",artwork:{atlas:"accessories",slot:1} },
  { category:"Charms",name:"Charm | Baby Karat CT",collection:"Counter-Strike 2",rarity:"Extraordinary",tone:"amber",symbol:"CT",artwork:{atlas:"accessories",slot:2} },
  { category:"Charms",name:"Charm | Baby Karat T",collection:"Counter-Strike 2",rarity:"Extraordinary",tone:"amber",symbol:"TT",artwork:{atlas:"accessories",slot:3} },
  { category:"Charms",name:"Charm | Hot Wurst",collection:"Counter-Strike 2",rarity:"High Grade",tone:"red",symbol:"HW",artwork:{atlas:"accessories",slot:4} },
  { category:"Charms",name:"Charm | Diamond Dog",collection:"Counter-Strike 2",rarity:"Extraordinary",tone:"cyan",symbol:"DD",artwork:{atlas:"accessories",slot:5} },
  { category:"Charms",name:"Charm | Chicken Lil'",collection:"Counter-Strike 2",rarity:"High Grade",tone:"mint",symbol:"CL",artwork:{atlas:"accessories",slot:6} },
  { category:"Charms",name:"Charm | Die-cast AK",collection:"Counter-Strike 2",rarity:"Remarkable",tone:"violet",symbol:"AK",artwork:{atlas:"accessories",slot:7} },
  { category:"Agents",name:"Sir Bloody Miami Darryl | The Professionals",collection:"The Professionals",rarity:"Master",tone:"pink",symbol:"MD",artwork:{atlas:"wearables",slot:0} },
  { category:"Agents",name:"Number K | The Professionals",collection:"The Professionals",rarity:"Master",tone:"violet",symbol:"NK",artwork:{atlas:"wearables",slot:1} },
  { category:"Agents",name:"Getaway Sally | The Professionals",collection:"The Professionals",rarity:"Superior",tone:"cyan",symbol:"GS",artwork:{atlas:"wearables",slot:2} },
  { category:"Agents",name:"Special Agent Ava | FBI",collection:"FBI",rarity:"Master",tone:"pink",symbol:"AV",artwork:{atlas:"wearables",slot:3} },
  { category:"Agents",name:"Lt. Commander Ricksaw | NSWC SEAL",collection:"NSWC SEAL",rarity:"Master",tone:"blue",symbol:"LR",artwork:{atlas:"wearables",slot:4} },
  { category:"Agents",name:"Cmdr. Frank 'Wet Sox' Baroud | SEAL Frogman",collection:"SEAL Frogman",rarity:"Master",tone:"cyan",symbol:"FB",artwork:{atlas:"wearables",slot:5} },
  { category:"Agents",name:"Blackwolf | Sabre",collection:"Sabre",rarity:"Superior",tone:"amber",symbol:"BW",artwork:{atlas:"wearables",slot:6} },
  { category:"Agents",name:"Vypa Sista of the Revolution | Guerrilla Warfare",collection:"Guerrilla Warfare",rarity:"Master",tone:"mint",symbol:"VS",artwork:{atlas:"wearables",slot:7} },
  { category:"Music Kits",name:"Music Kit | The Verkkars, EZ4ENCE",collection:"Counter-Strike 2",rarity:"High Grade",tone:"amber",symbol:"EZ",artwork:{atlas:"effects",slot:4} },
  { category:"Music Kits",name:"Music Kit | bbno$, u mad!",collection:"Counter-Strike 2",rarity:"High Grade",tone:"pink",symbol:"BB",artwork:{atlas:"effects",slot:5} },
  { category:"Music Kits",name:"Music Kit | Denzel Curry, ULTIMATE",collection:"Counter-Strike 2",rarity:"High Grade",tone:"red",symbol:"DC",artwork:{atlas:"effects",slot:6} },
  { category:"Music Kits",name:"Music Kit | Austin Wintory, Desert Fire",collection:"Counter-Strike 2",rarity:"High Grade",tone:"amber",symbol:"AW",artwork:{atlas:"effects",slot:7} },
  { category:"Music Kits",name:"Music Kit | AWOLNATION, I Am",collection:"Counter-Strike 2",rarity:"High Grade",tone:"cyan",symbol:"IA",artwork:{atlas:"effects",slot:8} },
  { category:"Music Kits",name:"Music Kit | Knock2, dashstar*",collection:"Counter-Strike 2",rarity:"High Grade",tone:"violet",symbol:"K2",artwork:{atlas:"effects",slot:9} },
  { category:"Medals",name:"2024 Service Medal",collection:"Counter-Strike 2",rarity:"Service Medal",tone:"blue",symbol:"24",artwork:{atlas:"effects",slot:0} },
  { category:"Medals",name:"2025 Service Medal",collection:"Counter-Strike 2",rarity:"Service Medal",tone:"mint",symbol:"25",artwork:{atlas:"effects",slot:1} },
  { category:"Medals",name:"Global Offensive Badge",collection:"Counter-Strike 2",rarity:"Collectible",tone:"amber",symbol:"GO",artwork:{atlas:"effects",slot:2} },
  { category:"Medals",name:"Operation Riptide Coin",collection:"Operation Riptide",rarity:"Operation Coin",tone:"cyan",symbol:"OR",artwork:{atlas:"effects",slot:3} },
  { category:"Medals",name:"Diamond Operation Broken Fang Coin",collection:"Operation Broken Fang",rarity:"Diamond",tone:"violet",symbol:"BF",artwork:{atlas:"effects",slot:4} },
  { category:"Medals",name:"Copenhagen 2024 Diamond Coin",collection:"Copenhagen 2024",rarity:"Diamond",tone:"cyan",symbol:"CP",artwork:{atlas:"effects",slot:5} },
  { category:"Medals",name:"Shanghai 2024 Diamond Coin",collection:"Shanghai 2024",rarity:"Diamond",tone:"pink",symbol:"SH",artwork:{atlas:"effects",slot:6} },
];
